version: '3.8'

services:
  backend-aws:
    build:
      context: ./e-commerce-junior-backend
      dockerfile: Dockerfile
    container_name: backend-aws
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge